### ISSUE TITLE
Productization / 2.3.2 - Test

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#205]
Productization test of version 2.3.2.RELEASE:
 * https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.3.2.RELEASE
 * https://mvnrepository.com/artifact/org.springframework.boot/spring-boot

The goal is to check the potential impact due to spring-boot being built with Gradle.

 - [x] Create the `sb-2.3.x` branch on the https://github.com/snowdrop/spring-boot-bom/ project
 - [x] Create the `sb-2.3.x` branch on the snowdrop examples
   - [x] cache-example
   - [x] circuit-breaker-example
   - [x] configmap-example
   - [x] crud-example
   - [ ] ~health-check-example~ as already had the sb-2.3.x
   - [x] istio-distributed-tracing-example
   - [x] messaging-work-queue-example
   - [x] rest-http-example
   - [x] secured-example
 - [x] Release Beta
 - [x] Update examples for release (`update for release`)
 - [x] Update the buildconfig
 - [ ] Release Productized version ER
 - [ ] Release Boosters/Examples

**Comment by jacobdotcosta** [comment]
Beta1 has been released.

**Comment by jacobdotcosta** [comment]
The tests for each of the examples have been launched with `./mvnw -B clean test` on the `sb-2.3.x` once updated to version 2.3.2.Beta1 and all were successfull.

```bash
SD_EXAMPLE_BRANCH_NAME=sb-2.3.x
for FORK_NAME in {'cache-example','circuit-breaker-example','configmap-example','crud-example','health-check-example','istio-distributed-tracing-example','messaging-work-queue-example','rest-http-example','secured-example'}
do
  git clone git@github.com:snowdrop/${FORK_NAME}.git
  pushd ${FORK_NAME}
  git checkout ${SD_EXAMPLE_BRANCH_NAME}
  ./mvnw -B clean test
  popd
  rm -Rf ${FORK_NAME}
done

```

**Comment by jacobdotcosta** [comment]
Beta1 had bugs and didn't have the overridden versions updated. This was manually done for Beta2.

**Comment by jacobdotcosta** [comment]
Trying to use bacon to create the build configuration at PNC2.

 - [x] downloaded the latest `bacon` snapshot 
 - [x] created the build-config file

## Result

Using the pig statement I get a NPE:

```
$ bacon pig configure spring-boot-2.3-PNC2 --skipBranchCheck --verbose
[DEBUG] - Log level set to DEBUG
[DEBUG] - Config file set from Constant to /home/xxx/.config/pnc-bacon/config.yaml
[ERROR] - Something wrong happened: 
java.lang.NullPointerException: null
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.lambda$execute$0(Pig.java:107)
        at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.execute(Pig.java:104)
        at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
        at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
        at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
        at org.jboss.pnc.bacon.cli.App.run(App.java:97)
        at org.jboss.pnc.bacon.cli.App.main(App.java:128)
[DEBUG] - Stacktrace
java.lang.NullPointerException: null
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.lambda$execute$0(Pig.java:107)
        at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.execute(Pig.java:104)
        at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
        at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
        at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
        at org.jboss.pnc.bacon.cli.App.run(App.java:97)
        at org.jboss.pnc.bacon.cli.App.main(App.java:128)

```

When I try adding the configuration manually I get an authentication error.

```
$ bacon pnc build-config create --environment-id 1 --project-id 450 --scm-repository-id 266 --scm-revision 2.3.2.Final  --build-script spring-boot-2.3-PNC2/build-config.yaml  spring-boot-parent-2.3
Enter your password: 
[ERROR] - Keycloak authentication failed!
[ERROR] - com.mashape.unirest.http.exceptions.UnirestException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Asked for help at the PNC Users chat room.

**Comment by jacobdotcosta** [comment]
This issue is blocked due to the impossibility of downloading the build repository. This repo is required to launch the marete tests.
