### ISSUE TITLE
Productization / Download the build repository build using bacon

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#214]
Once the build has finished the repository must be downloaded so the marete tests can be launched.

 - [x] Download the repository build using `bacon`
 - [x] Launch the `marete` tests
 - [x] Document the process

**Comment by jacobdotcosta** [comment]
This task is WIP as the download is currently failing. JIRA NCLSUP-100 has been opened.

```bash
$ bacon pig repo --removeGeneratedM2Dups --tempBuild --verbose /tmp/build-configurations/spring-boot-2.3-PNC2/
...
[ERROR] - Something wrong happened: 
java.lang.NullPointerException: null
        at org.jboss.pnc.bacon.pig.impl.common.DeliverableManager.getBuild(DeliverableManager.java:95)
        at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.generate(RepoManager.java:293)
        at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.prepare(RepoManager.java:84)
        at org.jboss.pnc.bacon.pig.PigFacade.generateRepo(PigFacade.java:307)
        at org.jboss.pnc.bacon.pig.Pig$GenerateRepository.doExecute(Pig.java:312)
        at org.jboss.pnc.bacon.pig.Pig$GenerateRepository.doExecute(Pig.java:300)
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.lambda$execute$0(Pig.java:110)
        at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.execute(Pig.java:104)
        at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
        at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
        at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
        at org.jboss.pnc.bacon.cli.App.run(App.java:97)
        at org.jboss.pnc.bacon.cli.App.main(App.java:128)
[DEBUG] - Stacktrace
java.lang.NullPointerException: null
        at org.jboss.pnc.bacon.pig.impl.common.DeliverableManager.getBuild(DeliverableManager.java:95)
        at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.generate(RepoManager.java:293)
        at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.prepare(RepoManager.java:84)
        at org.jboss.pnc.bacon.pig.PigFacade.generateRepo(PigFacade.java:307)
        at org.jboss.pnc.bacon.pig.Pig$GenerateRepository.doExecute(Pig.java:312)
        at org.jboss.pnc.bacon.pig.Pig$GenerateRepository.doExecute(Pig.java:300)
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.lambda$execute$0(Pig.java:110)
        at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
        at org.jboss.pnc.bacon.pig.Pig$PigCommand.execute(Pig.java:104)
        at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
        at org.aesh.command.impl.Executions$ExecutionImpl.execute(Executions.java:213)
        at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
        at org.jboss.pnc.bacon.cli.App.run(App.java:97)
        at org.jboss.pnc.bacon.cli.App.main(App.java:128)
```

**Comment by jacobdotcosta** [comment]
MR-50.
