### ISSUE TITLE
Fix job 060

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#568]
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.286 s <<< FAILURE! - in com.redhat.CompareBomsTest
[ERROR] com.redhat.CompareBomsTest.compare  Time elapsed: 3.265 s  <<< ERROR!
java.io.FileNotFoundException: /home/jenkins/agent/workspace/060_ReleaseQualityAssurance-job/build-comparator/effective.xml (No such file or directory)
	at com.redhat.CompareBomsTest.blacklistArtifacts(CompareBomsTest.java:95)
	at com.redhat.CompareBomsTest.compare(CompareBomsTest.java:53)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CompareBomsTest.compare:53->blacklistArtifacts:95 » FileNotFound /home/jenkins...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.497 s
[INFO] Finished at: 2021-09-28T14:12:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project build-comparator: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jenkins/agent/workspace/060_ReleaseQualityAssurance-job/build-comparator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jacobdotcosta** [comment]
Fixed the RCM URL to the new one.

**Comment by jacobdotcosta** [comment]
The blacklist report is still failing due to an unknown error.

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.infinispan:infinispan-bom:pom:12.1.7.Final-redhat-00001 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [maven.rhoar (http://indy.psi.redhat.com/api/group/static/, default, releases+snapshots)] @ line 141, column 19
[ERROR] Non-resolvable import POM: Could not transfer artifact io.dekorate:dekorate-spring-bom:pom:2.4.1.redhat-00003 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [maven.rhoar (http://indy.psi.redhat.com/api/group/static/, default, releases+snapshots)] @ line 150, column 19
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project dev.snowdrop:snowdrop-dependencies:2.4.9.Beta1-redhat-00002 (/home/jenkins/agent/workspace/060_ReleaseQualityAssurance-job/build-comparator/blacklist_build/rhoar-spring-boot-2.4.9.GA-maven-repository/maven-repository/dev/snowdrop/snowdrop-dependencies/2.4.9.Beta1-redhat-00002/snowdrop-dependencies-2.4.9.Beta1-redhat-00002.pom) has 2 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.infinispan:infinispan-bom:pom:12.1.7.Final-redhat-00001 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [maven.rhoar (http://indy.psi.redhat.com/api/group/static/, default, releases+snapshots)] @ line 141, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.dekorate:dekorate-spring-bom:pom:2.4.1.redhat-00003 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [maven.rhoar (http://indy.psi.redhat.com/api/group/static/, default, releases+snapshots)] @ line 150, column 19 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.768 s <<< FAILURE! - in com.redhat.CompareBomsTest
[ERROR] com.redhat.CompareBomsTest.compare  Time elapsed: 5.706 s  <<< ERROR!
java.io.FileNotFoundException: /home/jenkins/agent/workspace/060_ReleaseQualityAssurance-job/build-comparator/effective.xml (No such file or directory)
at com.redhat.CompareBomsTest.blacklistArtifacts(CompareBomsTest.java:95)
at com.redhat.CompareBomsTest.compare(CompareBomsTest.java:53)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   CompareBomsTest.compare:53->blacklistArtifacts:95 » FileNotFound /home/jenkins...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.172 s
[INFO] Finished at: 2021-10-11T09:00:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project build-comparator: There are test failures.
[ERROR]
[ERROR] Please refer to /home/jenkins/agent/workspace/060_ReleaseQualityAssurance-job/build-comparator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
