### ISSUE TITLE
Jenkins Openstack instance doesn't start

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#588]

**Comment by jacobdotcosta** [comment]
The POD was on `CrashLoopBackOff` state without any messages in the log file for the latest restarts so i'm redeploying.

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    3m55s                 default-scheduler  Successfully assigned ci/jenkinsci-0 to n119-test
  Warning  FailedMount  112s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[pipelines-volume], unattached volumes=[jenkins-config plugins jenkinsci-token-prwhv sc-config-volume pipelines-volume plugin-dir tmp-volume jenkins-home init-scripts admin-secret jenkins-cache]: timed out waiting for the condition
  Warning  FailedMount  107s (x9 over 3m55s)  kubelet            MountVolume.SetUp failed for volume "pipelines-volume" : configmap "pipelines-file" not found
```

**Comment by jacobdotcosta** [comment]
Logs obtained using `$ kubectl -n ci logs -p jenkinsci-0 init`

The problem is, again, version mismatch on the plugins.

```
io.jenkins.tools.pluginmanager.impl.AggregatePluginPrerequisitesNotMetException: Multiple plugin prerequisites not met:
Plugin git-parameter:0.9.13 (via git:4.10.0) depends on configuration-as-code:1.54, but there is an older version defined on the top level - configuration-as-code:1.53,
Plugin git-parameter:0.9.13 (via git:4.10.0) depends on git-client:3.10.0, but there is an older version defined on the top level - git-client:3.9.0,
Plugin github:1.34.1 (via git:4.10.0) depends on configuration-as-code:1.54, but there is an older version defined on the top level - configuration-as-code:1.53,
Plugin github:1.34.1 (via git:4.10.0) depends on git-client:3.10.0, but there is an older version defined on the top level - git-client:3.9.0,
Plugin pipeline-github-lib:1.0 (via git:4.10.0) depends on configuration-as-code:1.54, but there is an older version defined on the top level - configuration-as-code:1.53,
Plugin pipeline-github-lib:1.0 (via git:4.10.0) depends on git-client:3.10.0, but there is an older version defined on the top level - git-client:3.9.0
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:218)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:167)
	at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:70)
	Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin git-parameter:0.9.13 (via git:4.10.0) depends on configuration-as-code:1.54, but there is an older version defined on the top level - configuration-as-code:1.53
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1070)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:645)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:210)
		... 2 more
	Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin git-parameter:0.9.13 (via git:4.10.0) depends on git-client:3.10.0, but there is an older version defined on the top level - git-client:3.9.0
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1070)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:645)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:210)
		... 2 more
	Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin github:1.34.1 (via git:4.10.0) depends on configuration-as-code:1.54, but there is an older version defined on the top level - configuration-as-code:1.53
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1070)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:645)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:210)
		... 2 more
	Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin github:1.34.1 (via git:4.10.0) depends on git-client:3.10.0, but there is an older version defined on the top level - git-client:3.9.0
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1070)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:645)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:210)
		... 2 more
	Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin pipeline-github-lib:1.0 (via git:4.10.0) depends on configuration-as-code:1.54, but there is an older version defined on the top level - configuration-as-code:1.53
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1070)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:645)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:210)
		... 2 more
	Suppressed: io.jenkins.tools.pluginmanager.impl.PluginDependencyException: Plugin pipeline-github-lib:1.0 (via git:4.10.0) depends on git-client:3.10.0, but there is an older version defined on the top level - git-client:3.9.0
		at io.jenkins.tools.pluginmanager.impl.PluginManager.resolveRecursiveDependencies(PluginManager.java:1070)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.findPluginsAndDependencies(PluginManager.java:645)
		at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:210)
		... 2 more
```

**Comment by jacobdotcosta** [comment]
After fixing the plugin versions we have an error pulling the images from Docker.

```bash
kubectl -n ci describe pod  jenkinsci-0
...
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
...
  Normal   Pulling    3m45s (x3 over 4m29s)  kubelet            Pulling image "kiwigrid/k8s-sidecar:1.14.2"
  Warning  Failed     3m44s (x3 over 4m28s)  kubelet            Error: ErrImagePull
  Warning  Failed     3m44s (x2 over 4m14s)  kubelet            Failed to pull image "kiwigrid/k8s-sidecar:1.14.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kiwigrid/k8s-sidecar:1.14.2": failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/kiwigrid/k8s-sidecar/manifests/sha256:35654389f8a9b7816193a4811cf3ceb6cf309ece8874e84b3d2d8399e618059b: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Normal   BackOff    3m32s (x3 over 4m28s)  kubelet            Back-off pulling image "kiwigrid/k8s-sidecar:1.14.2"
  Warning  Failed     3m32s (x3 over 4m28s)  kubelet            Error: ImagePullBackOff
```

**Comment by jacobdotcosta** [comment]
The instance has been reinstalled.
