### ISSUE TITLE
Fix the errors on the 2.4.9 examples

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#612]
https://issues.redhat.com/browse/ENTSBT-951

- [x] https://github.com/snowdrop/configmap-example
- [x] https://github.com/snowdrop/circuit-breaker-example
- [x] https://github.com/snowdrop/rest-http-example
- [x] https://github.com/snowdrop/cache-example
- [x] https://github.com/snowdrop/crud-example
- [x] https://github.com/snowdrop/secured-example
- [x] https://github.com/snowdrop/messaging-work-queue-example
- [x] https://github.com/snowdrop/istio-distributed-tracing-example
- [x] https://github.com/snowdrop/health-check-example

**Comment by jacobdotcosta** [comment]
circuit breaker
```bash
$ mvn clean install -Popenshift -Ddekorate.deploy=true
...
[INFO] Reactor Summary for Spring Boot - Circuit Breaker Example 2.4.9-10-SNAPSHOT:
[INFO] 
[INFO] Spring Boot - Circuit Breaker Example .............. SUCCESS [  0.571 s]
[INFO] Spring Boot - Circuit Breaker Example - Greeting Service SUCCESS [ 50.821 s]
[INFO] Spring Boot - Circuit Breaker Example - Name Service SUCCESS [ 13.638 s]
[INFO] Spring Boot - Circuit Breaker Example - Tests ...... SUCCESS [  0.844 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 min
[INFO] Finished at: 2021-11-30T10:51:38+01:00
[INFO] ------------------------------------------------------------------------
```
```bash
$ mvn clean verify
...
[INFO] Reactor Summary for Spring Boot - Circuit Breaker Example 2.4.9-10-SNAPSHOT:
[INFO] 
[INFO] Spring Boot - Circuit Breaker Example .............. SUCCESS [  0.262 s]
[INFO] Spring Boot - Circuit Breaker Example - Greeting Service SUCCESS [ 22.837 s]
[INFO] Spring Boot - Circuit Breaker Example - Name Service SUCCESS [  7.748 s]
[INFO] Spring Boot - Circuit Breaker Example - Tests ...... SUCCESS [  0.854 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.948 s
[INFO] Finished at: 2021-11-30T10:57:06+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
```bash
$  mvn clean verify -Popenshift,openshift-it
...
[INFO] Running dev.snowdrop.example.OpenShiftIT
[INFO] Found version:1.20
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.649 s <<< FAILURE! - in dev.snowdrop.example.OpenShiftIT
[ERROR] testCircuitBreaker  Time elapsed: 0.448 s  <<< ERROR!
java.lang.NullPointerException
	at dev.snowdrop.example.OpenShiftIT.getBaseUrlByRouteName(OpenShiftIT.java:121)
	at dev.snowdrop.example.OpenShiftIT.setup(OpenShiftIT.java:51)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OpenShiftIT.setup:51->getBaseUrlByRouteName:121 NullPointer
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ spring-boot-circuit-breaker-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Spring Boot - Circuit Breaker Example 2.4.9-10-SNAPSHOT:
[INFO] 
[INFO] Spring Boot - Circuit Breaker Example .............. SUCCESS [  0.163 s]
[INFO] Spring Boot - Circuit Breaker Example - Greeting Service SUCCESS [ 17.667 s]
[INFO] Spring Boot - Circuit Breaker Example - Name Service SUCCESS [  7.274 s]
[INFO] Spring Boot - Circuit Breaker Example - Tests ...... FAILURE [  4.396 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.679 s
[INFO] Finished at: 2021-11-30T13:19:19+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default) on project spring-boot-circuit-breaker-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /z/dev/client/redhat/forks-github/circuit-breaker-example/tests/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
```

**Comment by jacobdotcosta** [comment]
https://github.com/snowdrop/crud-example/issues/85

**Comment by jacobdotcosta** [comment]
rest-http-example

```bash
$ sh run_tests_with_s2i.sh

...

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running dev.snowdrop.example.ManagedOpenShiftIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.003 s - in dev.snowdrop.example.ManagedOpenShiftIT
[INFO] Found version:1.20
[INFO] Running dev.snowdrop.example.UnmanagedOpenShiftIT
Apply test resources from:jar:file:/z/dev/client/redhat/forks-github/rest-http-example/target/rest-http-2.4.9-10-SNAPSHOT.jar!/META-INF/dekorate/openshift.yml
[INFO] Found version:1.20
[INFO] Found version:1.20
[INFO] Deleting: Service name:rest-http. Deleted:true
[INFO] Deleting: BuildConfig name:rest-http. Deleted:true
[INFO] Deleting: DeploymentConfig name:rest-http. Deleted:true
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.623 s - in dev.snowdrop.example.UnmanagedOpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ rest-http ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.660 s
[INFO] Finished at: 2021-12-01T15:42:14+01:00
[INFO] Final Memory: 58M/228M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
Cache example fully tested.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.595 s
[INFO] Finished at: 2021-12-02T10:06:59+01:00
[INFO] Final Memory: 27M/114M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
Restarting the tests as the scripts to create the openshift resources are also included.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spring Boot - Cache Example ........................ SUCCESS [  0.700 s]
[INFO] Spring Boot - Cache Example - Cute Name Service .... SUCCESS [  9.109 s]
[INFO] Spring Boot - Cache Example - Greeting Service ..... SUCCESS [ 11.438 s]
[INFO] Spring Boot - Caching Example - Tests .............. SUCCESS [ 35.811 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.385 s
[INFO] Finished at: 2021-12-07T13:57:52+01:00
[INFO] Final Memory: 82M/300M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
Secured examples success

```
[INFO] Running dev.snowdrop.example.ManagedOpenShiftIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in dev.snowdrop.example.ManagedOpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ rest-secured ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.765 s
[INFO] Finished at: 2021-12-07T14:10:01+01:00
[INFO] Final Memory: 57M/228M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
configmap-example success
```
[INFO] Found version:1.20
[INFO] Deleting: Service name:configmap. Deleted:true
[INFO] Deleting: BuildConfig name:configmap. Deleted:true
[INFO] Deleting: DeploymentConfig name:configmap. Deleted:true
[INFO] Deleting: Route name:configmap. Deleted:true
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.937 s - in dev.snowdrop.example.UnmanagedOpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ configmap ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.854 s
[INFO] Finished at: 2021-12-07T14:27:37+01:00
[INFO] Final Memory: 52M/214M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
circuit-breaker-example success

```
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ spring-boot-circuit-breaker-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spring Boot - Circuit Breaker Example .............. SUCCESS [  0.273 s]
[INFO] Spring Boot - Circuit Breaker Example - Greeting Service SUCCESS [ 23.363 s]
[INFO] Spring Boot - Circuit Breaker Example - Name Service SUCCESS [  9.690 s]
[INFO] Spring Boot - Circuit Breaker Example - Tests ...... SUCCESS [02:08 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:41 min
[INFO] Finished at: 2021-12-07T15:40:22+01:00
[INFO] Final Memory: 76M/288M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
rest-http-example test succsess

```
[INFO] Found version:1.20
[INFO] Found version:1.20
[INFO] Deleting: Service name:rest-http. Deleted:true
[INFO] Deleting: BuildConfig name:rest-http. Deleted:true
[INFO] Deleting: DeploymentConfig name:rest-http. Deleted:true
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.776 s - in dev.snowdrop.example.UnmanagedOpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ rest-http ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.745 s
[INFO] Finished at: 2021-12-07T16:01:45+01:00
[INFO] Final Memory: 58M/234M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
health-check-example success

```
[INFO] Deleting: Service name:health-check. Deleted:true
[INFO] Deleting: BuildConfig name:health-check. Deleted:true
[INFO] Deleting: DeploymentConfig name:health-check. Deleted:true
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 64.598 s - in dev.snowdrop.example.UnmanagedOpenShiftIT
[INFO] Running dev.snowdrop.example.ManagedOpenShiftIT
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in dev.snowdrop.example.ManagedOpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 4, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ health-check ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2021-12-07T16:50:01+01:00
[INFO] Final Memory: 55M/228M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
messaging-work-queue-example success
```
[INFO] Found version:1.20
[INFO] Running dev.snowdrop.example.OpenShiftIT
[INFO] Found version:1.20
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.283 s - in dev.snowdrop.example.OpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ spring-boot-messaging-example-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spring Boot - Messaging - Work Queue Example - Parent SUCCESS [  1.471 s]
[INFO] Spring Boot - Messaging - Work Queue Example - Frontend SUCCESS [  8.801 s]
[INFO] Spring Boot - Messaging - Work Queue Example - Worker SUCCESS [  5.033 s]
[INFO] Spring Boot - Messaging - Work Queue Example - Integration Tests SUCCESS [ 18.710 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.779 s
[INFO] Finished at: 2021-12-07T19:21:46+01:00
[INFO] Final Memory: 86M/320M
[INFO] ------------------------------------------------------------------------
```

**Comment by jacobdotcosta** [comment]
crud-example success

```
[INFO] Found version:1.20
[INFO] Deleting: Service name:crud. Deleted:true
[INFO] Deleting: BuildConfig name:crud. Deleted:true
[INFO] Deleting: DeploymentConfig name:crud. Deleted:false
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.765 s - in dev.snowdrop.example.UnmanagedOpenShiftIT
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ crud ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.912 s
[INFO] Finished at: 2021-12-07T19:42:53+01:00
[INFO] Final Memory: 63M/240M
[INFO] ------------------------------------------------------------------------
```
