### ISSUE TITLE
Jenkins is failing when jobs are execued

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#655]
When any of the Vertx and Narayana release jobs is executed it is failing in the *Initial workspace cleanup* stage with a timeout. Seems that the `maven-3` container is not being downloaded correctly.

```
java.io.IOException: Timed out waiting for websocket connection. You should increase the value of system property org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout currently set at 30 seconds
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.doLaunch(ContainerExecDecorator.java:451)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:338)
```

In the log the following message is shown.

```
2022-01-04 08:24:08.016+0000 [id=35]	SEVERE	hudson.triggers.SafeTimerTask#run: Timer task org.csanchez.jenkins.plugins.kubernetes.KubernetesClientProvider$UpdateConnectionCount@72aadbe3 failed
java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient io.fabric8.kubernetes.client.HttpClientAware.getHttpClient()'
```

**Comment by jacobdotcosta** [comment]
Fixed by:
* https://issues.jenkins.io/browse/JENKINS-67483
* https://stackoverflow.com/questions/70524933/jenkins-with-kubernetes-client-plugin-nosuchmethoderror

**Comment by jacobdotcosta** [comment]
Fixed by https://gitlab.cee.redhat.com/snowdrop/infra-prod/-/merge_requests/70
