### ISSUE TITLE
Error testing Istio Example - module applications don't start

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#848]
When executing the istio example tests they fail with the following error.

```

java.lang.NullPointerException
	at me.snowdrop.istio.dt.OpenshiftIT.getBaseUrlByRouteName(OpenshiftIT.java:135)
	at me.snowdrop.istio.dt.OpenshiftIT.setup(OpenshiftIT.java:40)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OpenshiftIT.setup:40->getBaseUrlByRouteName:135 NullPointer
```

**Comment by jacobdotcosta** [comment]
The POD fails to start.

```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/spring-boot-istio-distributed-tracing-cute-name-service-2.5.12-3-SNAPSHOT.jar
no main manifest attribute, in /deployments/spring-boot-istio-distributed-tracing-cute-name-service-2.5.12-3-SNAPSHOT.jar
```

**Comment by jacobdotcosta** [comment]
When executing the istio example tests they fail with the following error.

```
SizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/spring-boot-istio-distributed-tracing-greeting-service-2.5.12-3-SNAPSHOT.jar  
no main manifest attribute, in /deployments/spring-boot-istio-distributed-tracing-greeting-service-2.5.12-3-SNAPSHOT.jar

[INFO] ---
[INFO] Cleaning up...
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.072 s <<< FAILURE! - in me.snowdrop.istio.dt.OpenshiftIT
[ERROR] tracingTest  Time elapsed: 3.827 s  <<< ERROR!
java.lang.NullPointerException
	at me.snowdrop.istio.dt.OpenshiftIT.getBaseUrlByRouteName(OpenshiftIT.java:135)
	at me.snowdrop.istio.dt.OpenshiftIT.setup(OpenshiftIT.java:40)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OpenshiftIT.setup:40->getBaseUrlByRouteName:135 NullPointer
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ spring-boot-istio-distributed-tracing-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.196 s
[INFO] Finished at: 2022-06-09T15:14:54+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default) on project spring-boot-istio-distributed-tracing-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ajc102/docs/redhat/forks-github/istio-distributed-tracing-example/tests/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
```

**Comment by jacobdotcosta** [comment]
The istio example is now working correctly.
