### ISSUE TITLE
Release Narayana Spring Boot Starter Beta with Spring Boot 2.7.2

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#875]
Release Narayana Spring Boot Starter with 2.7.2

- [x] Bump Narayana SB Version to `2.7.2`
  - https://github.com/snowdrop/narayana-spring-boot/pull/93
- [x] Release Narayana SB Starter Beta upstream
  - `2.6.7.Beta1`: https://github.com/snowdrop/narayana-spring-boot/releases/tag/2.6.7.Beta1

**Comment by jacobdotcosta** [comment]
`mvn test` is failing with the following error.

```
2022-07-26 11:47:48.192 ERROR 10925 --- [           main] javax.management.mbeanserver             : The LogManager accessed before the "java.util.logging.manager" system property was set to "org.jboss.logmanager.LogManager". Results may be unexpected.
2022-07-26 11:47:49.199  INFO 10925 --- [           main] m.s.narayana.sample.UserServiceTest      : Started UserServiceTest in 3.91 seconds (JVM running for 5.826)
2022-07-26 11:47:49.309  INFO 10925 --- [ntContainer#0-1] com.arjuna.ats.arjuna                    : ARJUNA012170: TransactionStatusManager started on port 38121 and host 127.0.0.1 with service com.arjuna.ats.arjuna.recovery.ActionStatusService
Executor ---> Attempting to create a user named Richard
JMS Logger ---> Created a new user Richard
JMS Logger ---> Created a new user Little Finger
Executor ---> Current users: Little Finger, Richard
JMS Logger ---> Created a new user King Slayer
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 6.073 s <<< FAILURE! - in me.snowdrop.narayana.sample.UserServiceTest
[ERROR] me.snowdrop.narayana.sample.UserServiceTest.shouldCreateAndListUser  Time elapsed: 0.96 s  <<< ERROR!
java.lang.NoSuchMethodError: 'org.assertj.core.api.ListAssert org.assertj.core.api.ListAssert.containsOnlyOnce(java.lang.Object[])'
	at me.snowdrop.narayana.sample.UserServiceTest.shouldCreateAndListUser(UserServiceTest.java:36)

[ERROR] me.snowdrop.narayana.sample.UserServiceTest.shouldNotCreateDuplicateUsers  Time elapsed: 0.536 s  <<< ERROR!
java.lang.NoSuchMethodError: 'org.assertj.core.api.ListAssert org.assertj.core.api.ListAssert.containsOnlyOnce(java.lang.Object[])'
	at me.snowdrop.narayana.sample.UserServiceTest.shouldNotCreateDuplicateUsers(UserServiceTest.java:48)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   UserServiceTest.shouldCreateAndListUser:36 NoSuchMethod 'org.assertj.core.api....
[ERROR]   UserServiceTest.shouldNotCreateDuplicateUsers:48 NoSuchMethod 'org.assertj.cor...
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Narayana Spring Boot :: parent ..................... SUCCESS [  2.825 s]
[INFO] Narayana Spring Boot :: core ....................... SUCCESS [  4.404 s]
[INFO] Narayana Spring Boot :: starter .................... SUCCESS [  5.034 s]
[INFO] Narayana Spring Boot :: starter integration tests .. SUCCESS [  1.828 s]
[INFO] Narayana Spring Boot :: Openshift :: Recovery Controller SUCCESS [  0.719 s]
[INFO] Narayana Spring Boot :: samples .................... SUCCESS [  0.101 s]
[INFO] Narayana Spring Boot :: samples :: 2 datasources ... SUCCESS [  0.172 s]
[INFO] Narayana Spring Boot :: samples :: 2 phase commit .. FAILURE [  8.780 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.047 s
[INFO] Finished at: 2022-07-26T11:47:51+02:00
[INFO] Final Memory: 42M/147M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project narayana-spring-boot-sample-2pc: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ajc102/docs/redhat/github/narayana-spring-boot/narayana-spring-boot-samples/narayana-spring-boot-sample-2pc/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :narayana-spring-boot-sample-2pc
```

**Comment by jacobdotcosta** [comment]
Upgraded Java version from `11.0.14-tem` to `11.0.16-tem` and fixed the problem.
