### ISSUE TITLE
Release SB 2.7.8 DR

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/team#991]
- [x] Check overridden versions
- [x] Align examples for SB version
- [x] Check CVE
- [x] Update build configuration
- [x] Launch DR build

**Comment by jacobdotcosta** [comment]
Updated the CVE documentation checking the ones that might be included.

**Comment by jacobdotcosta** [comment]
Dekorate build is failing...
```
[INFO] Dekorate :: Code Formatter ......................... SUCCESS [ 14.288 s]
[INFO] Dekorate ........................................... FAILURE [ 23.550 s]
[INFO] Dekorate :: Documentation Templates ................ SKIPPED
[INFO] Dekorate :: Core ................................... SKIPPED
[INFO] Dekorate :: Annotations ............................ SKIPPED
[INFO] Dekorate :: Annotations :: Options ................. SKIPPED
[INFO] Dekorate :: Annotations :: Docker .................. SKIPPED
[INFO] Dekorate :: Annotations :: Kubernetes .............. SKIPPED
[INFO] Dekorate :: Annotations :: S2i ..................... SKIPPED
[INFO] Dekorate :: Annotations :: Openshift ............... SKIPPED
[INFO] Dekorate :: Annotations :: Prometheus .............. SKIPPED
[INFO] Dekorate :: Frameworks ............................. SKIPPED
[INFO] Dekorate :: Frameworks :: Spring Boot .............. SKIPPED
[INFO] Dekorate :: Annotations :: Minikube ................ SKIPPED
[INFO] Dekorate :: Starters ............................... SKIPPED
[INFO] Dekorate :: Starters :: Kubernetes ................. SKIPPED
[INFO] Dekorate :: Starters :: Kubernetes :: Spring ....... SKIPPED
[INFO] Dekorate :: Annotations :: ServiceBinding CRD ...... SKIPPED
[INFO] Dekorate :: Annotations :: Kind .................... SKIPPED
[INFO] Dekorate :: Annotations :: Helm .................... SKIPPED
[INFO] Dekorate :: Annotations :: CertManager CRD ......... SKIPPED
[INFO] Dekorate :: Testing ................................ SKIPPED
[INFO] Dekorate :: Testing :: Core ........................ SKIPPED
[INFO] Dekorate :: Testing :: Openshift ................... SKIPPED
[INFO] Dekorate :: Testing :: Kubernetes .................. SKIPPED
[INFO] Dekorate :: Starters :: Kubernetes :: Junit ........ SKIPPED
[INFO] Dekorate :: Starters :: Openshift .................. SKIPPED
[INFO] Dekorate :: Starters :: Openshift :: Spring ........ SKIPPED
[INFO] Dekorate :: Starters :: Openshift :: Junit ......... SKIPPED
[INFO] Dekorate :: Starters :: Service Binding ............ SKIPPED
[INFO] Dekorate :: Starters :: ServiceBinding :: Spring ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.005 s
[INFO] Finished at: 2023-01-31T10:44:50+00:00
[INFO] Final Memory: 40M/333M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.12.2:format (default) on project dekorate-bom: Execution default of goal net.revelc.code.formatter:formatter-maven-plugin:2.12.2:format failed: Plugin net.revelc.code.formatter:formatter-maven-plugin:2.12.2 or one of its dependencies could not be resolved: Could not find artifact io.dekorate:dekorate-formatter:jar:2.11.6 in indy-mvn (https://localhost:8443/api/folo/track/build-AWVEC3RV6DAAE/maven/group/build-AWVEC3RV6DAAE) -> [Help 1]
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.12.2:format (default) on project dekorate-spring-bom: Execution default of goal net.revelc.code.formatter:formatter-maven-plugin:2.12.2:format failed: Plugin net.revelc.code.formatter:formatter-maven-plugin:2.12.2 or one of its dependencies could not be resolved: Failure to find io.dekorate:dekorate-formatter:jar:2.11.6 in https://localhost:8443/api/folo/track/build-AWVEC3RV6DAAE/maven/group/build-AWVEC3RV6DAAE was cached in the local repository, resolution will not be reattempted until the update interval of indy-mvn has elapsed or updates are forced -> [Help 1]
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.12.2:format (default) on project dekorate-project: Execution default of goal net.revelc.code.formatter:formatter-maven-plugin:2.12.2:format failed: Plugin net.revelc.code.formatter:formatter-maven-plugin:2.12.2 or one of its dependencies could not be resolved: Failure to find io.dekorate:dekorate-formatter:jar:2.11.6 in https://localhost:8443/api/folo/track/build-AWVEC3RV6DAAE/maven/group/build-AWVEC3RV6DAAE was cached in the local repository, resolution will not be reattempted until the update interval of indy-mvn has elapsed or updates are forced -> [Help 1]
[ERROR] 
```

**Comment by jacobdotcosta** [comment]
The Dekorate problem has been fixed by excluding the formatter on the release.

**Comment by jacobdotcosta** [comment]
Error when building on PNC.

```

[INFO ] - Repackaging the repository
[DEBUG] - Adding repository documents
[ERROR] - null, Error: null
[DEBUG] - Full trace
java.lang.NullPointerException: null
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.addAdditionalArtifacts(RepoManager.java:382)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.repackage(RepoManager.java:324)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.buildGroup(RepoManager.java:251)
	at org.jboss.pnc.bacon.pig.impl.repo.RepoManager.prepare(RepoManager.java:157)
	at org.jboss.pnc.bacon.pig.PigFacade.generateRepo(PigFacade.java:521)
	at org.jboss.pnc.bacon.pig.PigFacade.run(PigFacade.java:218)
	at org.jboss.pnc.bacon.pig.Pig$Run.doExecute(Pig.java:264)
	at org.jboss.pnc.bacon.pig.Pig$Run.doExecute(Pig.java:174)
	at org.jboss.pnc.bacon.pig.Pig$PigCommand.call(Pig.java:162)
	at org.jboss.pnc.bacon.pig.Pig$PigCommand.call(Pig.java:97)
```

**Comment by cmoulliard** [comment]
> [DEBUG] - Adding repository documents

Is it a problem that you have t check with PNC team ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
No, it was a problem with the build configuration file. It's fixed.

**Comment by jacobdotcosta** [comment]
Duplicates:

```
[INFO] 
[ERROR] org.jboss.qa.marete.MavenRepoTest.uniqueArtifacts(org.jboss.qa.marete.MavenRepoTest)
[ERROR]   Run 1: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson:jackson-base] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 2: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson.module:jackson-modules-java8] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 3: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson.core:jackson-core] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 4: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson.core:jackson-databind] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 5: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson.datatype:jackson-datatype-jsr310] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 6: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml:oss-parent] 
Expected size: 1 but was: 2 in:
["43.0.0.redhat-00002", "43.0.0.temporary-redhat-00005"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 7: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson:jackson-bom] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 8: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.sun.activation:all] 
Expected size: 1 but was: 2 in:
["1.2.2.redhat-00001", "1.2.1.redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 9: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson:jackson-parent] 
Expected size: 1 but was: 2 in:
["2.13.0.temporary-redhat-00005", "2.13.0.redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 10: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for jakarta.activation:jakarta.activation-api] 
Expected size: 1 but was: 2 in:
["1.2.2.redhat-00001", "1.2.1.redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 11: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for com.fasterxml.jackson.core:jackson-annotations] 
Expected size: 1 but was: 2 in:
["2.13.1.redhat-00002", "2.13.1.temporary-redhat-00002"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
[ERROR]   Run 12: MavenRepoTest.uniqueArtifacts:401->lambda$uniqueArtifacts$35:404 [There must be no duplicates for org.apache:apache] 
Expected size: 1 but was: 2 in:
["24.0.0.redhat-00001", "23.0.0.redhat-00001"]
at MavenRepoTest.lambda$uniqueArtifacts$35(MavenRepoTest.java:404)
```
